### ISSUE TITLE
Window size

### ISSUE THREAD

**Issue by jhautefeuille** [georgewalton/Sandals#2]
Is it possible to change main window size ?

Thank you for this module.

**Comment by georgewalton** [comment]
@jhautefeuille No problem! I've updated it so the window context works correctly, it wasn't before for some reason.

Now you should be able to change window attributes using TkInter methods, e.g.;

``` python
from sandals import *

with window("My window") as w:
    w.geometry('{}x{}'.format(300,500))
    w.resizable(width=FALSE, height=TRUE)
```

**Comment by jhautefeuille** [comment]
Nice thank you, but I've an error (Python 3.4 on Linux) : 

```
Traceback (most recent call last):
File "main.py", line 206, in <module>
main()
File "main.py", line 35, in main
w.geometry('{}x{}'.format(640,480))
AttributeError: 'Frame' object has no attribute 'geometry'
```

Maybe

https://stackoverflow.com/questions/8934334/why-does-the-geometry-method-work-with-a-delay

give you information.

**Comment by georgewalton** [comment]
Yeah, this is the error I was getting too, you need to use the updated sandals.py

**Comment by jhautefeuille** [comment]
Nice, it's ok now, thank you.
